# Generated by Django 4.0.3 on 2022-04-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0002_fee_balance_fee_paid_scores_biology_scores_chemistry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='adm_no',
        ),
        migrations.AddField(
            model_name='student',
            name='adm_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
