# Generated by Django 4.0.3 on 2022-04-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0003_remove_teacher_adm_no_student_adm_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=20)),
            ],
        ),
    ]
