# Generated by Django 4.0.3 on 2022-04-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0006_alter_staff_email_alter_teacher_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
